<a href="https://colab.research.google.com/github/kji49968941-netizen/kjane/blob/main/%EC%9D%B4%EC%82%B0%EC%88%98%ED%95%99_5%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_202521460%EA%B9%80%EC%A0%9C%EC%9D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

A = {1,2,3}
B = {2,3,4}
R = {(1,2),(2,3),(3,2),(3,4)}
print("관계R:",R)

관계R: {(2, 3), (3, 2), (1, 2), (3, 4)}


In [2]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

A = {1,2,3}
B = {2,3,4}
R = {(1,2),(2,3),(3,2),(3,4)}

A_list = sorted(A)
B_list = sorted(B)

relation_matrix = np.zeros((len(A_list),len(B_list)),dtype = int)

for i , a in enumerate(A_list): #i = index a = value
  for j , b in enumerate(B_list):# j = index b = value
    if(a,b) in R:
      relation_matrix[i,j] = 1

print("관계 행렬(rows:A, columns:B):")
print(relation_matrix)


관계 행렬(rows:A, columns:B):
[[1 0 0]
 [0 1 0]
 [1 0 1]]


In [3]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

A = {1,2,3}
B = {2,3,4}
C = {'x','y'}
R = {(1,2),(2,3),(3,2),(3,4)}
S = {(2,'x'),(3,'y'),(4,'x')}

composed_relation = set()

for(a,b1) in R:
  for(b2,c) in S:
    if b1 == b2:
      composed_relation.add((a,c))

print("\n합성 관계 R.S:",composed_relation)


합성 관계 R.S: {(3, 'x'), (2, 'y'), (1, 'x')}
